<a href="https://colab.research.google.com/github/SachinSingh1412/ml/blob/main/3_1_Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0015476109999998933


In [4]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0013594979999997925


Numpy Arrays

In [5]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a.shape

(4,)

In [9]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [11]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [12]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.43701787 0.19574676 0.83743642 0.88534061]
 [0.29550446 0.53325135 0.99548293 0.65633332]
 [0.08110396 0.5957745  0.62868511 0.94698846]]


In [17]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[14 71 63 74 92]
 [83 90 59 14 89]
 [49 99 44 41 28]]


In [18]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [19]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [20]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [21]:
c = np.random.randint(10,90,(5,5))
print(c)

[[54 84 66 33 14]
 [32 84 57 78 80]
 [43 15 17 18 24]
 [56 60 55 14 57]
 [53 70 60 84 89]]


In [22]:
# array dimension
print(c.shape)

(5, 5)


In [23]:
# number of dimensions
print(c.ndim)

2


In [24]:
# number of elements in an array
print(c.size)

25


In [25]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [26]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [27]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [28]:
print(a)
print(b)

[[7 4 8]
 [9 5 9]
 [4 7 4]]
[[16 15 11]
 [19 13 18]
 [14 11 19]]


In [29]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[23 19 19]
 [28 18 27]
 [18 18 23]]
[[ -9 -11  -3]
 [-10  -8  -9]
 [-10  -4 -15]]
[[112  60  88]
 [171  65 162]
 [ 56  77  76]]
[[0.4375     0.26666667 0.72727273]
 [0.47368421 0.38461538 0.5       ]
 [0.28571429 0.63636364 0.21052632]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[4 7 7]
 [3 9 9]
 [4 9 7]]
[[11 12 10]
 [19 14 16]
 [10 19 15]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 19 17]
 [22 23 25]
 [14 28 22]]
[[ -7  -5  -3]
 [-16  -5  -7]
 [ -6 -10  -8]]
[[ 44  84  70]
 [ 57 126 144]
 [ 40 171 105]]
[[0.36363636 0.58333333 0.7       ]
 [0.15789474 0.64285714 0.5625    ]
 [0.4        0.47368421 0.46666667]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 2 2]
 [8 0 7]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 8]
 [2 0]
 [2 7]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 1 0]
 [2 5 9]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[8 2]
 [1 5]
 [0 9]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 3 7]
 [4 6 6]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 3]
 [7 4]
 [6 6]]
(3, 2)
